### ISSUE TITLE
Creating .js files when running

### ISSUE THREAD

**Issue by adamvictorclever** [cschroeter/ts-strictify#1]
Hey, thanks for making this - it seems really cool and useful! I was trying it out and noticed that running it created a ton of .js files (presumably one for each .ts file), which is not what I want. Could this be fixed by adding `--noEmit` when running `tsc` for typechecking in the code?

**Comment by cschroeter** [comment]
Hey yeah it takes your project's `tsconfig.json` and just takes the config from there. So setting `noEmit` there would do the trick. But since it is a typechecking tool, would make sense to have `noEmit` enabled by default

**Comment by cschroeter** [comment]
You can now do `ts-strictify --noEmit true`. For all other options, have a look here https://github.com/cschroeter/ts-strictify#options
