### ISSUE TITLE
UnhandledPromiseRejectionWarning when executing ts-strictify

### ISSUE THREAD

**Issue by rjdestigter** [cschroeter/ts-strictify#2]
I'm running into the following error while trying to run _ts-strictify_. Possibly because my project is located in a subfolder of the repository?

I'm debugging it myself at the moment trying to find out why it is breaking.

```
(node:22856) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 128 (Unknown system error -128): git merge-base --fork-point master
    at makeError (~\projects\foobar\client\node_modules\ts-strictify\node_modules\execa\lib\error.js:58:11)
    at handlePromise (~\foobar\client\node_modules\ts-strictify\node_modules\execa\index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:22856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rjdestigter** [comment]
When I change the script to use my develop branch instead of master it works.

**Comment by rjdestigter** [comment]
https://stackoverflow.com/questions/52505453/git-merge-base-fork-point-ref-is-yielding-nothing may have information that could be related to this issue.

**Comment by cschroeter** [comment]
This script need a bit more polishment. It is still highly opionated e.g. it is trying always to find where a branch was forked from `master` 💁‍♀️

If you can provide me a simple repository that reproduce your issue and I will happily look into it ✌️

**Comment by evertbouw** [comment]
Ran into this as well, made a fork with hard coded `develop` branch. If I can find some time I can try to add a target branch option.

**Comment by cschroeter** [comment]
With **0.5.0** you can define a different branch then master `--targetBranch [string] [default: "master"]`.

Also all promises have a proper exception handling.
